# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  #win: circleci/windows@2.4.1
  aws-s3: circleci/aws-s3@3.0
  macos: circleci/macos@2.1.0
# Define a job to be invoked later in a workflow
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  AcceptanceTestMac:
    macos:
      xcode: 12.5.1
    steps:
      #- run:
          #name: Install Chrome
          #command: |
            #$Path = $TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "http://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path\$Installer
      - run:
          name: Install node@16
          command: brew unlink node; brew install node@16; brew link --overwrite node@16 --force
      - run:
          command: node --version
          name: Check updated node version
      - checkout
      - run:
          name: Install Packages
          command: cd engageAutomation; npm install
      #- run:
          #defaults write com.apple.Safari AllowRemoteAutomation 1
      #- run:
          #sudo safaridriver --enable
      - macos/add-safari-permissions
      - run:
          name: Run Tests_engage (MacOS + Safari Branch)
          command: cd engageAutomation; npm test -- --reportdir=$(date +%d-%m-%Y-%H-%M-%S) --appType=$APP_TYPE --testEnv=$TEST_ENV --testExecFile=AcceptanceNew.json  --windowWidth=1600 --windowHeight=900 --browserCapability=desktop-safari-1920 || true
      - aws-s3/sync:
          arguments: |
          from: './engageAutomation/output/reports/'
          to: 's3://engage-qa-testreports/$APP_TYPE/$TEST_ENV'  
      - run:
          name: Install Packages of Mailer
          command: cd engageAutomation; npm install yargs fs nodemailer;
      - run:
          name: After Job - Send mail
          command: |
            cd engageAutomation/core/utils; node mailer.js --appType=$APP_TYPE --testEnv=$TEST_ENV --projectName=$CIRCLE_PROJECT_REPONAME --branchName=$CIRCLE_BRANCH --buildNumber=$CIRCLE_BUILD_NUM --mailingList=$MAILINGLIST --emailId=$emailId --emailPwd=$emailPwd --jobResult=$CIRCLE_BUILD_URL --triggerSource=$triggerSource
workflows:
  engage:
    jobs:
      - AcceptanceTestMac